/* Department To-Do: shared teacher completion follow-up */
(()=>{
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const db=()=>parent.portfolioSupabase,u=()=>parent.PORTFOLIO_USER;
async function me(){const {data}=await db().from('portfolio_profiles').select('role,display_name').eq('user_id',u().id).maybeSingle();return data||{role:'teacher',display_name:u().email}}
async function tasks(){const {data,error}=await db().from('department_todos').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}
async function completions(){const {data,error}=await db().from('department_todo_completions').select('task_id,user_id,completed_at');if(error)throw error;return data||[]}
async function profiles(){const [{data:stateRow,error:stateErr},{data:accounts,error:accountErr}]=await Promise.all([db().from('portfolio_state').select('data').eq('id','main').maybeSingle(),db().from('portfolio_profiles').select('user_id,display_name,email,role').order('display_name')]);if(stateErr)throw stateErr;if(accountErr)throw accountErr;const teacherNames=(stateRow?.data?.teachers||[]).map(t=>String(t.name||'').trim()).filter(Boolean);return {teacherNames,accounts:accounts||[]}}
const soon=x=>{if(!x.due_date)return false;const a=new Date(),b=new Date(x.due_date+'T23:59:59');return b>=a&&(b-a)<=2*86400000};
window.renderTodoSummary=async()=>{const e=document.getElementById('todoSummary');if(!e||!db()||!u())return;try{const [a,c]=await Promise.all([tasks(),completions()]),mine=new Set(c.filter(x=>x.user_id===u().id).map(x=>x.task_id)),active=a.filter(x=>!mine.has(x.id));e.innerHTML=`<b>${active.length}</b>${active.some(x=>x.priority==='High')?'<span class="todo-urgent" title="Highly Urgent">!</span>':''}${active.some(soon)?'<span class="todo-soon" title="Coming Soon">•</span>':''}`}catch(err){console.error(err)}};
window.openTodoAdd=async()=>{const p=await me();if(p.role!=='admin')return alert('Only the coordinator can add department tasks.');openModal(`<h2>📋 Add Department Task</h2><label>Task</label><input id="todoTitle" placeholder="Task title"><label>Assign to</label><select id="todoAssign"><option>All Department</option></select><label>Due date</label><input id="todoDue" type="date"><label>Priority</label><select id="todoPriority"><option>Normal</option><option>High</option><option>Low</option></select><div class="actions"><button class="btn primary" onclick="saveTodo()">Save</button><button class="btn" onclick="closeModal()">Cancel</button></div>`)};
window.saveTodo=async()=>{const title=todoTitle.value.trim();if(!title)return alert('Add a task title.');const {error}=await db().from('department_todos').insert({title,assigned_to:todoAssign.value,due_date:todoDue.value||null,priority:todoPriority.value,created_by:u().id});if(error)return alert(error.message);closeModal();renderTodoSummary()};
async function toggle(id,done){if(done){await db().from('department_todo_completions').delete().eq('task_id',id).eq('user_id',u().id)}else{await db().from('department_todo_completions').insert({task_id:id,user_id:u().id})}openTodoList();renderTodoSummary()}
window.toggleTodoShared=toggle;
window.deleteTodoShared=async id=>{if(!confirm('Delete this task?'))return;await db().from('department_todos').delete().eq('id',id);openTodoList();renderTodoSummary()};
window.openTodoProgress=async id=>{try{const [pinfo,cs]=await Promise.all([profiles(),completions()]),teacherNames=pinfo.teacherNames,accounts=pinfo.accounts.filter(x=>x.role==='teacher'),doneIds=new Set(cs.filter(x=>x.task_id===id).map(x=>x.user_id)),norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,''),rows=teacherNames.map(name=>{const n=norm(name),acct=accounts.find(a=>{const dn=norm(a.display_name),em=norm((a.email||'').split('@')[0]);return dn===n||em===n||dn.includes(n)||n.includes(dn)});return {name,done:!!(acct&&doneIds.has(acct.user_id)),connected:!!acct}}),count=rows.filter(x=>x.done).length,pct=rows.length?Math.round(count/rows.length*100):0;openModal(`<div class="folder-head"><div><h2>Teacher Progress</h2><small><b>${count}/${rows.length} Completed</b> · ${pct}%</small></div></div><div class="progress" style="margin:14px 0 18px"><div class="bar" style="width:${pct}%"></div></div><div class="list">${rows.length?rows.map(t=>`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:14px"><b>${esc(t.name)}</b><span style="font-weight:800">${t.done?'✅ Completed':'⏳ Pending'}</span></div>`).join(''):'<div class="empty-state">No teachers found in Lesson Plans.</div>'}</div><div class="actions"><button class="btn" onclick="openTodoList()">Back</button></div>`)}catch(err){console.error(err);alert('Teacher progress could not load. Please refresh and try again.')}};
window.openTodoList=async()=>{try{const [a,c,p]=await Promise.all([tasks(),completions(),me()]),mine=new Set(c.filter(x=>x.user_id===u().id).map(x=>x.task_id));openModal(`<div class="folder-head"><div><h2>📋 Department To-Do</h2><small>Department follow-up tasks</small></div>${p.role==='admin'?'<button class="btn primary" onclick="openTodoAdd()">＋ Add Task</button>':''}</div><div class="list">${a.length?a.map(x=>{const done=mine.has(x.id),status=done?'✓ Completed':x.priority==='High'?'Highly Urgent':soon(x)?'Coming Soon':'Upcoming';return `<div class="item"><b>${esc(x.title)}</b><small>${esc(x.assigned_to)} · ${x.due_date||'No due date'} · ${status}</small><div class="actions"><button class="btn ${done?'':'primary'}" onclick="toggleTodoShared(${x.id},${done})">${done?'Reopen':'✓ Mark Completed'}</button>${p.role==='admin'?`<button class="btn" onclick="openTodoProgress(${x.id})">Teacher Progress</button><button class="btn danger" onclick="deleteTodoShared(${x.id})">Delete</button>`:''}</div></div>`}).join(''):'<div class="empty-state">No tasks added yet.</div>'}</div><div class="modal-footer"><button class="btn" onclick="closeModal()">Close</button></div>`)}catch(err){console.error(err);alert('To-Do could not load. Please refresh and try again.')}};
window.installDepartmentTodo=()=>{const old=document.getElementById('departmentTodoCard');if(old)old.remove();if(document.getElementById('departmentTodoNav')){renderTodoSummary();return}const nav=document.querySelector('.nav');if(!nav)return;const btn=document.createElement('button');btn.id='departmentTodoNav';btn.className='todo-nav-btn';btn.onclick=openTodoList;btn.innerHTML=`☑ To-Do <span id="todoSummary"></span>`;nav.appendChild(btn);renderTodoSummary()};
installDepartmentTodo();
})();