/* Shared Teacher Share & Inspire library backed by Supabase Storage. */
(function(){
 const BUCKET='portfolio-files'; let rows=[];
 const wait=()=>{if(!parent.portfolioSupabase||!parent.PORTFOLIO_USER){setTimeout(wait,400);return;} init();};
 const client=()=>parent.portfolioSupabase,user=()=>parent.PORTFOLIO_USER;
 async function profile(){const {data}=await client().from('portfolio_profiles').select('display_name,role').eq('user_id',user().id).maybeSingle();return data||{display_name:user().email,role:'teacher'};}
 async function load(){const {data,error}=await client().from('portfolio_uploads').select('id,owner_id,teacher_name,category,title,file_name,storage_path,created_at,metadata').order('created_at',{ascending:false});if(error){console.error(error);return;}rows=data||[];refreshCounts();}
 function refreshCounts(){if(!window.cats||!window.shareGrid)return; const cards=[...shareGrid.querySelectorAll('.sharecard')]; cards.forEach((card,i)=>{const cat=cats[i]&&cats[i][1];if(!cat)return;const n=rows.filter(r=>r.category===cat).length;let badge=card.querySelector('.shared-library-count');if(!badge){badge=document.createElement('div');badge.className='shared-library-count';card.appendChild(badge);}badge.innerHTML=`<b>${n}</b> shared file${n===1?'':'s'} from colleagues <button class="btn" onclick="openSharedLibrary('${cat.replace(/'/g,"\\'")}')">Shared Library</button>`;});}
 window.openSharedLibrary=async function(cat){await load();const list=rows.filter(r=>r.category===cat);openModal(`<div class="folder-head"><div><h2>👥 ${esc(cat)} · Shared Library</h2><small>Files shared by English Department colleagues</small></div><button class="btn primary" onclick="uploadSharedFile('${cat.replace(/'/g,"\\'")}')">＋ Upload File</button></div>${list.length?`<div class="clean-list">${list.map(r=>`<div class="clean-upload"><div class="file-icon">📄</div><div class="file-info"><b>${esc(r.title||r.file_name||'Shared file')}</b><small>${esc(r.teacher_name||'Teacher')} · ${r.created_at?new Date(r.created_at).toLocaleDateString():''}</small></div><div class="file-actions"><button class="btn open-btn" onclick="openSharedFile(${r.id})">Open</button>${r.owner_id===user().id?`<button class="btn delete-btn" onclick="deleteSharedFile(${r.id})">Delete</button>`:''}</div></div>`).join('')}</div>`:'<div class="empty-state">No colleague files shared in this category yet.</div>'}<div class="modal-footer"><button class="btn" onclick="closeModal()">Close</button></div>`);};
 window.uploadSharedFile=function(cat){openModal(`<div class="folder-head"><div><h2>Upload to Shared Library</h2><small>Your colleagues will be able to open this file.</small></div></div><label>Title</label><input id="sharedTitle" placeholder="Material title"><label>Choose file</label><input id="sharedFile" type="file"><div class="actions"><button class="btn primary" onclick="saveSharedFile('${cat.replace(/'/g,"\\'")}')">Share File</button><button class="btn" onclick="openSharedLibrary('${cat.replace(/'/g,"\\'")}')">Cancel</button></div>`);};
 window.saveSharedFile=async function(cat){const f=document.getElementById('sharedFile').files[0],title=document.getElementById('sharedTitle').value.trim();if(!f)return alert('Choose a file.');const p=await profile(),safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${user().id}/${Date.now()}-${safe}`;const {error:up}=await client().storage.from(BUCKET).upload(path,f);if(up)return alert('Upload failed: '+up.message);const {error}=await client().from('portfolio_uploads').insert({owner_id:user().id,teacher_name:p.display_name||user().email,category:cat,title:title||f.name,file_name:f.name,storage_path:path,metadata:{size:f.size,type:f.type}});if(error){await client().storage.from(BUCKET).remove([path]);return alert('Could not save file: '+error.message);}await openSharedLibrary(cat);};
 window.openSharedFile=async function(id){const r=rows.find(x=>x.id===id);if(!r)return;const {data,error}=await client().storage.from(BUCKET).createSignedUrl(r.storage_path,300);if(error)return alert('Could not open file.');window.open(data.signedUrl,'_blank','noopener');};
 window.deleteSharedFile=async function(id){const r=rows.find(x=>x.id===id);if(!r||r.owner_id!==user().id||!confirm('Delete your shared file?'))return;await client().storage.from(BUCKET).remove([r.storage_path]);const {error}=await client().from('portfolio_uploads').delete().eq('id',id);if(error)return alert('Could not delete file.');await openSharedLibrary(r.category);};
 async function init(){await load();setInterval(load,60000);}
 wait();
})();

/* Professional department theme: deep navy + refined teal + warm champagne. Visual only. */
(function(){const s=document.createElement('style');s.textContent=`
:root{--navy:#17324d!important;--teal:#2f6f73!important;--gold:#c7a96b!important;--bg:#f5f7f8!important;--card:#ffffff!important;--line:#dbe3e8!important;--muted:#6d7d89!important;--green:#4f806d!important;--red:#a85f5f!important}
body{background:#f5f7f8!important;color:#263d4d!important}.hero{background:linear-gradient(135deg,#17324d 0%,#244b61 58%,#2f6f73 100%)!important;color:#fff!important;border-bottom:0!important;box-shadow:0 8px 24px rgba(23,50,77,.16)!important}.hero h1{color:#fff!important}.hero p,.hero small{color:#dce8ed!important}.starbar{background:#f4efe4!important;color:#5f5137!important;border-bottom:1px solid #e4d7bd!important}.nav button{background:#fff!important;color:#405a6b!important;border:1px solid #d9e2e7!important}.nav button.active{background:#17324d!important;color:#fff!important;border-color:#17324d!important}.card,.teacher,.sharecard,.mini,.item,.day{background:#fff!important;border-color:#dbe3e8!important;box-shadow:0 5px 18px rgba(31,55,73,.055)!important}.sectionhead h2,.card h2,.card h3,.sharecard h3{color:#17324d!important}.btn{background:#eef2f4!important;color:#29485a!important;border-color:#dbe3e8!important}.btn:hover{filter:brightness(.975)}.btn.primary,.open-btn{background:#2f6f73!important;color:#fff!important;border-color:#2f6f73!important}.btn.gold{background:#e8dcc2!important;color:#5b4927!important;border-color:#d9c69d!important}.btn.danger,.delete-btn{background:#f8eeee!important;color:#955656!important;border-color:#ead4d4!important}.assessment-card .card-intro,.support-card .card-intro{background:#f7f9fa!important;border-color:#dbe3e8!important}.assessment-card .card-intro h3,.support-card .card-intro h3{color:#17324d!important}.assessment-card .card-intro p,.support-card .card-intro p{color:#6d7d89!important}.teacher-list-row{background:#fff!important;border-color:#dbe3e8!important}.teacher-list-row .name,.file-info b,.folder-head h2{color:#17324d!important}.progress{background:#e6ecef!important}.bar{background:#2f6f73!important}.done .bar{background:#4f806d!important}.low .bar{background:#c7a96b!important}.notice{background:#f7f3ea!important;border-color:#e5dac2!important;color:#65583e!important}.box{background:#fff!important;border-color:#dbe3e8!important;box-shadow:0 20px 55px rgba(23,50,77,.18)!important}.clean-upload{background:#fbfcfc!important;border-color:#dbe3e8!important}.file-icon{background:#edf3f4!important}.shared-library-count{background:#f1f5f6!important;color:#526a78!important}
`;document.head.appendChild(s)})();