/* Shared Teacher Share & Inspire library backed by Supabase Storage. */
(function(){
 const BUCKET='portfolio-files'; let rows=[];
 const wait=()=>{if(!parent.portfolioSupabase||!parent.PORTFOLIO_USER){setTimeout(wait,400);return;} init();};
 const client=()=>parent.portfolioSupabase,user=()=>parent.PORTFOLIO_USER;
 async function profile(){const {data}=await client().from('portfolio_profiles').select('display_name,role').eq('user_id',user().id).maybeSingle();return data||{display_name:user().email,role:'teacher'};}
 async function load(){const {data,error}=await client().from('portfolio_uploads').select('id,owner_id,teacher_name,category,title,file_name,storage_path,created_at,metadata').order('created_at',{ascending:false});if(error){console.error(error);return;}rows=data||[];refreshCounts();}
 function refreshCounts(){if(!window.cats||!window.shareGrid)return; const cards=[...shareGrid.querySelectorAll('.sharecard')]; cards.forEach((card,i)=>{const cat=cats[i]&&cats[i][1];if(!cat)return;const n=rows.filter(r=>r.category===cat).length;let badge=card.querySelector('.shared-library-count');if(!badge){badge=document.createElement('div');badge.className='shared-library-count';card.appendChild(badge);}badge.innerHTML=`<b>${n}</b> shared file${n===1?'':'s'} from colleagues <button class="btn" onclick="openSharedLibrary('${cat.replace(/'/g,"\\'")}')">Shared Library</button>`;});}
 window.openSharedLibrary=async function(cat){await load();const list=rows.filter(r=>r.category===cat);openModal(`<div class="folder-head"><div><h2>👥 ${esc(cat)} · Shared Library</h2><small>Files shared by English Department colleagues</small></div><button class="btn primary" onclick="uploadSharedFile('${cat.replace(/'/g,"\\'")}')">＋ Upload File</button></div>${list.length?`<div class="clean-list">${list.map(r=>`<div class="clean-upload"><div class="file-icon">📄</div><div class="file-info"><b>${esc(r.title||r.file_name||'Shared file')}</b><small>${esc(r.teacher_name||'Teacher')} · ${r.created_at?new Date(r.created_at).toLocaleDateString():''}</small></div><div class="file-actions"><button class="btn open-btn" onclick="openSharedFile(${r.id})">Open</button>${r.owner_id===user().id?`<button class="btn delete-btn" onclick="deleteSharedFile(${r.id})">Delete</button>`:''}</div></div>`).join('')}</div>`:'<div class="empty-state">No colleague files shared in this category yet.</div>'}<div class="modal-footer"><button class="btn" onclick="closeModal()">Close</button></div>`);};
 window.uploadSharedFile=function(cat){openModal(`<div class="folder-head"><div><h2>Upload to Shared Library</h2><small>Your colleagues will be able to open this file.</small></div></div><label>Title</label><input id="sharedTitle" placeholder="Material title"><label>Choose file</label><input id="sharedFile" type="file"><div class="actions"><button class="btn primary" onclick="saveSharedFile('${cat.replace(/'/g,"\\'")}')">Share File</button><button class="btn" onclick="openSharedLibrary('${cat.replace(/'/g,"\\'")}')">Cancel</button></div>`);};
 window.saveSharedFile=async function(cat){const f=document.getElementById('sharedFile').files[0],title=document.getElementById('sharedTitle').value.trim();if(!f)return alert('Choose a file.');const p=await profile(),safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${user().id}/${Date.now()}-${safe}`;const {error:up}=await client().storage.from(BUCKET).upload(path,f);if(up)return alert('Upload failed: '+up.message);const {error}=await client().from('portfolio_uploads').insert({owner_id:user().id,teacher_name:p.display_name||user().email,category:cat,title:title||f.name,file_name:f.name,storage_path:path,metadata:{size:f.size,type:f.type}});if(error){await client().storage.from(BUCKET).remove([path]);return alert('Could not save file: '+error.message);}await openSharedLibrary(cat);};
 window.openSharedFile=async function(id){const r=rows.find(x=>x.id===id);if(!r)return;const {data,error}=await client().storage.from(BUCKET).createSignedUrl(r.storage_path,300);if(error)return alert('Could not open file.');window.open(data.signedUrl,'_blank','noopener');};
 window.deleteSharedFile=async function(id){const r=rows.find(x=>x.id===id);if(!r||r.owner_id!==user().id||!confirm('Delete your shared file?'))return;await client().storage.from(BUCKET).remove([r.storage_path]);const {error}=await client().from('portfolio_uploads').delete().eq('id',id);if(error)return alert('Could not delete file.');await openSharedLibrary(r.category);};
 async function init(){await load();setInterval(load,60000);}
 wait();
})();