(()=>{
const d=document;
const ALLOWED=/\.(pdf|doc|docx|xls|xlsx)$/i;
const ACCEPT='.pdf,.doc,.docx,.xls,.xlsx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('EnglishDepartmentPortfolioFiles',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('supportPlans'))r.result.createObjectStore('supportPlans',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getAll(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readonly').objectStore('supportPlans').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function put(x){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readwrite').objectStore('supportPlans').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(id){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readwrite').objectStore('supportPlans').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function validFiles(list){return [...(list||[])].filter(f=>ALLOWED.test(f.name))}
async function saveSupportSelection(type,files,label){const teacher=(d.getElementById('supportTeacher')?.value||'').trim();if(!teacher)return alert('Please add the teacher name.');const fs=validFiles(files);if(!fs.length)return alert('Please choose PDF, Word or Excel files.');await put({id:Date.now()+'-'+Math.random().toString(36).slice(2),type,teacher,folder:label||'Uploaded Files',created:Date.now(),files:fs.map(f=>({name:f.name,path:f.webkitRelativePath||f.name,type:f.type,data:f}))});openSupportPlans(type)}
window.openSupportPlans=async function(type){const title=type==='diagnostic'?'Diagnostic Analysis':'CA Analysis';const rows=(await getAll()).filter(x=>x.type===type).sort((a,b)=>b.created-a.created);const body=`<div style="margin-bottom:14px"><h3 style="margin:0 0 10px">📁 ${title}</h3><label>Teacher Name</label><input id="supportTeacher" placeholder="Enter teacher name"><small style="display:block;color:#7b878c;margin:7px 0 12px">Teacher name is required for every upload.</small><div class="actions"><label class="btn primary" style="cursor:pointer">+ Upload File<input id="supportFileInput" type="file" accept="${ACCEPT}" multiple hidden></label><label class="btn gold" style="cursor:pointer">+ Upload Folder<input id="supportFolderInput" type="file" webkitdirectory directory multiple hidden></label></div></div><div id="supportRows">${rows.length?rows.map(x=>`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><div><b>📂 ${esc(x.folder)}</b><br><small><b>${esc(x.teacher||'Teacher not recorded')}</b> · ${x.files.length} file${x.files.length===1?'':'s'} · ${new Date(x.created).toLocaleDateString()}</small></div><div class="actions"><button class="btn" onclick="openSupportFolder('${x.id}')">Open Folder</button><button class="btn danger" onclick="deleteSupportFolder('${x.id}','${type}')">Delete</button></div></div>`).join(''):'<div class="notice">No support plans uploaded yet.</div>'}</div>`;if(typeof openModal==='function')openModal(body);setTimeout(()=>{const fi=d.getElementById('supportFileInput');if(fi)fi.onchange=()=>saveSupportSelection(type,fi.files,'Uploaded Files');const fo=d.getElementById('supportFolderInput');if(fo)fo.onchange=()=>{const fs=[...fo.files];const folder=fs.length?((fs[0].webkitRelativePath||fs[0].name).split('/')[0]):'Uploaded Folder';saveSupportSelection(type,fs,folder)}},0)};
window.openSupportFolder=async function(id){const x=(await getAll()).find(v=>v.id===id);if(!x)return;const html=`<h3>📂 ${esc(x.folder)}</h3><p style="color:#7b878c"><b>Teacher: ${esc(x.teacher||'Not recorded')}</b> · ${x.files.length} uploaded file${x.files.length===1?'':'s'}</p>${x.files.map((f,i)=>`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><span>${esc(f.path)}</span><button class="btn" onclick="openSupportFile('${id}',${i})">Open</button></div>`).join('')}`;if(typeof openModal==='function')openModal(html)};
window.openSupportFile=async function(id,i){const x=(await getAll()).find(v=>v.id===id);if(!x||!x.files[i])return;const u=URL.createObjectURL(x.files[i].data);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)};
window.deleteSupportFolder=async function(id,type){if(!confirm('Delete this uploaded folder?'))return;await del(id);openSupportPlans(type)};

/* LESSON PLANS: teacher name is visible and recorded automatically from selected teacher */
window.uploadPlan=function(i){const t=state.teachers[i];openModal(`<h2>${esc(t.name)} · Week ${state.week}</h2><label>Teacher Name</label><input id="pteacher" value="${esc(t.name)}" readonly><label>Grade / class</label><input id="pgrade"><label>Lesson Plans Folder</label><input id="pfolder" type="file" webkitdirectory directory multiple><div class="actions"><button class="btn primary" onclick="saveLessonFolder(${i})">Upload Folder</button><button class="btn" onclick="closeModal()">Cancel</button></div>`)};
window.saveLessonFolder=function(i){const teacher=(d.getElementById('pteacher')?.value||state.teachers[i].name||'').trim();if(!teacher)return alert('Please add the teacher name.');const grade=(d.getElementById('pgrade')?.value||'').trim();const chosen=[...(d.getElementById('pfolder')?.files||[])];const files=validFiles(chosen);if(!files.length)return alert('Choose a folder containing PDF, Word or Excel lesson plans.');const folder=((chosen[0].webkitRelativePath||chosen[0].name).split('/')[0])||`Week ${state.week} Lesson Plans`;const k=weekKey();state.teachers[i].plans[k]=state.teachers[i].plans[k]||[];let remaining=files.length;const entry={teacher,grade,file:folder,folder:true,files:[],date:new Date().toISOString()};files.forEach(file=>{const r=new FileReader();r.onload=()=>{entry.files.push({name:file.name,path:file.webkitRelativePath||file.name,data:r.result,type:file.type});remaining--;if(!remaining){state.teachers[i].plans[k].push(entry);save();closeModal();openFolder(i)}};r.readAsDataURL(file)})};
window.openLessonFolder=function(i,j){const k=weekKey(),entry=(state.teachers[i].plans[k]||[])[j];if(!entry||!entry.folder)return;openModal(`<h2>📂 ${esc(entry.file)}</h2><p><b>Teacher: ${esc(entry.teacher||state.teachers[i].name)}</b> · ${esc(state.term)} · Week ${state.week}</p>${entry.files.map((f,n)=>`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><span>${esc(f.path)}</span><button class="btn" onclick="openLessonFolderFile(${i},${j},${n})">Open</button></div>`).join('')}<div class="actions"><button class="btn" onclick="openFolder(${i})">Back</button></div>`)};
window.openLessonFolderFile=function(i,j,n){const entry=(state.teachers[i].plans[weekKey()]||[])[j];const f=entry?.files?.[n];if(!f)return;openStoredFile(f.data,f.name)};
window.lessonRows=function(i){const arr=state.teachers[i].plans[weekKey()]||[];if(!arr.length)return '<div class="notice">No lesson plans uploaded for this week.</div>';return arr.map((p,j)=>p.folder?`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><div><b>📂 ${esc(p.file)}</b><br><small><b>${esc(p.teacher||state.teachers[i].name)}</b> · ${esc(p.grade||'')} · ${p.files?.length||0} files</small></div><div class="actions"><button class="btn primary" onclick="openLessonFolder(${i},${j})">Open Folder</button><button class="btn danger" onclick="deletePlan(${i},'${weekKey()}',${j})">Delete</button></div></div>`:`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><div><b>${esc(p.file||'Lesson Plan')}</b><br><small><b>${esc(p.teacher||state.teachers[i].name)}</b> · ${esc(p.grade||'')}</small></div><div class="actions"><button class="btn" ${p.data?`onclick="openStoredFile(state.teachers[${i}].plans['${weekKey()}'][${j}].data,state.teachers[${i}].plans['${weekKey()}'][${j}].file)"`:'disabled'}>Open</button><button class="btn danger" onclick="deletePlan(${i},'${weekKey()}',${j})">Delete</button></div></div>`).join('')};

/* Share & Inspire: teacher name required */
window.addShare=function(cat){openModal(`<h2>Add ${esc(cat)}</h2><label>Teacher Name</label><input id="steacher" placeholder="Enter teacher name"><label>Title</label><input id="stitle"><label>Grade / class</label><input id="sgrade"><label>Short description</label><textarea id="sdesc"></textarea><label>Upload file(s)</label><input id="sfile" type="file" accept="${ACCEPT}" multiple><label>Or upload a folder</label><input id="sfolder" type="file" webkitdirectory directory multiple><div class="actions"><button class="btn primary" onclick="saveShareEnhanced('${String('CAT').replace(/'/g,"\\'")}')">Add Evidence</button><button class="btn" onclick="closeModal()">Cancel</button></div>`.replace("'CAT'",JSON.stringify(cat)))};
window.saveShareEnhanced=function(cat){const title=(d.getElementById('stitle')?.value||'').trim(),teacher=(d.getElementById('steacher')?.value||'').trim(),grade=(d.getElementById('sgrade')?.value||'').trim(),desc=(d.getElementById('sdesc')?.value||'').trim();if(!teacher)return alert('Please add the teacher name.');if(!title)return alert('Please add a title.');const files=validFiles([...(d.getElementById('sfile')?.files||[]),...(d.getElementById('sfolder')?.files||[])]);if(!files.length){state.shares.push({term:state.term,cat,title,teacher,grade,desc,file:'',data:'',date:new Date().toISOString()});save();closeModal();return}let remaining=files.length;files.forEach(file=>{const r=new FileReader();r.onload=()=>{state.shares.push({term:state.term,cat,title,teacher,grade,desc,file:file.webkitRelativePath||file.name,data:r.result,date:new Date().toISOString()});remaining--;if(!remaining){save();closeModal()}};r.readAsDataURL(file)})};
setTimeout(()=>{[...d.querySelectorAll('main > .notice')].forEach(n=>{if(/^Important:/i.test((n.textContent||'').trim()))n.remove()})},0);
})();