(()=>{
const d=document;
const ALLOWED=/\.(pdf|doc|docx|xls|xlsx)$/i;
const ACCEPT='.pdf,.doc,.docx,.xls,.xlsx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const jsq=s=>String(s||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");
function validFiles(list){return [...(list||[])].filter(f=>ALLOWED.test(f.name))}
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('EnglishDepartmentPortfolioFiles',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('supportPlans'))r.result.createObjectStore('supportPlans',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getAll(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readonly').objectStore('supportPlans').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function put(x){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readwrite').objectStore('supportPlans').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(id){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readwrite').objectStore('supportPlans').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function saveSupportSelection(type,files,label){const teacher=(d.getElementById('supportTeacher')?.value||'').trim();if(!teacher)return alert('Please add the teacher name.');const fs=validFiles(files);if(!fs.length)return alert('Please choose PDF, Word or Excel files.');await put({id:Date.now()+'-'+Math.random().toString(36).slice(2),type,teacher,folder:label||'Uploaded Files',created:Date.now(),files:fs.map(f=>({name:f.name,path:f.webkitRelativePath||f.name,type:f.type,data:f}))});openSupportPlans(type)}
window.openSupportPlans=async function(type){const title=type==='diagnostic'?'Diagnostic Analysis':'CA Analysis';const rows=(await getAll()).filter(x=>x.type===type).sort((a,b)=>b.created-a.created);const body=`<div style="margin-bottom:14px"><h3>📁 ${title}</h3><label>Teacher Name</label><input id="supportTeacher" placeholder="Enter teacher name"><div class="actions"><label class="btn primary" style="cursor:pointer">+ Upload File<input id="supportFileInput" type="file" accept="${ACCEPT}" multiple hidden></label><label class="btn gold" style="cursor:pointer">+ Upload Folder<input id="supportFolderInput" type="file" webkitdirectory directory multiple hidden></label></div></div>${rows.length?rows.map(x=>`<div class="item"><b>📂 ${esc(x.folder)}</b><small><b>${esc(x.teacher)}</b> · ${x.files.length} files</small><div class="actions"><button class="btn" onclick="openSupportFolder('${x.id}')">Open Folder</button><button class="btn danger" onclick="deleteSupportFolder('${x.id}','${type}')">Delete</button></div></div>`).join(''):'<div class="notice">No support plans uploaded yet.</div>'}`;openModal(body);setTimeout(()=>{supportFileInput.onchange=()=>saveSupportSelection(type,supportFileInput.files,'Uploaded Files');supportFolderInput.onchange=()=>{const fs=[...supportFolderInput.files];saveSupportSelection(type,fs,fs.length?(fs[0].webkitRelativePath||'Uploaded Folder').split('/')[0]:'Uploaded Folder')}},0)};
window.openSupportFolder=async function(id){const x=(await getAll()).find(v=>v.id===id);if(!x)return;openModal(`<h3>📂 ${esc(x.folder)}</h3><p><b>Teacher: ${esc(x.teacher)}</b></p>${x.files.map((f,i)=>`<div class="item"><span>${esc(f.path)}</span><button class="btn" onclick="openSupportFile('${id}',${i})">Open</button></div>`).join('')}`)};
window.openSupportFile=async function(id,i){const x=(await getAll()).find(v=>v.id===id);if(!x?.files[i])return;const u=URL.createObjectURL(x.files[i].data);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)};
window.deleteSupportFolder=async function(id,type){if(!confirm('Delete this uploaded folder?'))return;await del(id);openSupportPlans(type)};

window.uploadPlan=function(i){const t=state.teachers[i];openModal(`<h2>${esc(t.name)} · Week ${state.week}</h2><label>Teacher Name</label><input id="pteacher" value="${esc(t.name)}" readonly><label>Grade / class</label><input id="pgrade"><label>Lesson Plans Folder</label><input id="pfolder" type="file" webkitdirectory directory multiple><div class="actions"><button class="btn primary" onclick="saveLessonFolder(${i})">Upload Folder</button><button class="btn" onclick="closeModal()">Cancel</button></div>`)};
window.saveLessonFolder=function(i){const teacher=(pteacher.value||state.teachers[i].name).trim(),grade=pgrade.value.trim(),chosen=[...pfolder.files],files=validFiles(chosen);if(!files.length)return alert('Choose a folder containing PDF, Word or Excel lesson plans.');const folder=(chosen[0].webkitRelativePath||chosen[0].name).split('/')[0],k=weekKey();state.teachers[i].plans[k]=state.teachers[i].plans[k]||[];let remaining=files.length;const entry={teacher,grade,file:folder,folder:true,files:[],date:new Date().toISOString()};files.forEach(file=>{const r=new FileReader();r.onload=()=>{entry.files.push({name:file.name,path:file.webkitRelativePath||file.name,data:r.result,type:file.type});if(!--remaining){state.teachers[i].plans[k].push(entry);save();closeModal();openFolder(i)}};r.readAsDataURL(file)})};
window.openLessonFolder=function(i,j){const entry=(state.teachers[i].plans[weekKey()]||[])[j];if(!entry)return;openModal(`<h2>📂 ${esc(entry.file)}</h2><p><b>Teacher: ${esc(entry.teacher||state.teachers[i].name)}</b></p>${(entry.files||[]).map((f,n)=>`<div class="item"><span>${esc(f.path)}</span><button class="btn" onclick="openLessonFolderFile(${i},${j},${n})">Open</button></div>`).join('')}`)};
window.openLessonFolderFile=function(i,j,n){const f=state.teachers[i].plans[weekKey()]?.[j]?.files?.[n];if(f)openStoredFile(f.data,f.name)};
window.lessonRows=function(i){const arr=state.teachers[i].plans[weekKey()]||[];if(!arr.length)return '<div class="notice">No lesson plans uploaded for this week.</div>';return arr.map((p,j)=>`<div class="item"><b>📂 ${esc(p.file||'Lesson Plans')}</b><small><b>${esc(p.teacher||state.teachers[i].name)}</b> · ${p.files?.length||0} files</small><div class="actions"><button class="btn primary" onclick="openLessonFolder(${i},${j})">Open Folder</button><button class="btn danger" onclick="deletePlan(${i},'${weekKey()}',${j})">Delete</button></div></div>`).join('')};

/* Share & Inspire — fixed button quoting and real folder upload */
window.addShare=function(cat){const c=jsq(cat);openModal(`<h2>Add ${esc(cat)}</h2><label>Teacher Name</label><input id="steacher" placeholder="Enter teacher name"><label>Title</label><input id="stitle" placeholder="Enter title"><label>Grade / class</label><input id="sgrade"><label>Short description</label><textarea id="sdesc"></textarea><label>Upload PDF, Word or Excel file(s)</label><input id="sfile" type="file" accept="${ACCEPT}" multiple><label>Or upload a complete folder</label><input id="sfolder" type="file" webkitdirectory directory multiple><div class="actions"><button id="shareUploadBtn" class="btn primary">Upload</button><button class="btn" onclick="closeModal()">Cancel</button></div>`);setTimeout(()=>{const b=d.getElementById('shareUploadBtn');if(b)b.onclick=()=>saveShareEnhanced(cat)},0)};
window.saveShareEnhanced=function(cat){const teacher=(d.getElementById('steacher')?.value||'').trim(),title=(d.getElementById('stitle')?.value||'').trim(),grade=(d.getElementById('sgrade')?.value||'').trim(),desc=(d.getElementById('sdesc')?.value||'').trim();if(!teacher)return alert('Please add the teacher name.');if(!title)return alert('Please add a title.');const folderChosen=[...(d.getElementById('sfolder')?.files||[])],fileChosen=[...(d.getElementById('sfile')?.files||[])],chosen=folderChosen.length?folderChosen:fileChosen,files=validFiles(chosen);if(!files.length)return alert('Please choose PDF, Word, Excel files or a folder containing them.');const isFolder=folderChosen.length>0,folderName=isFolder?(folderChosen[0].webkitRelativePath||folderChosen[0].name).split('/')[0]:title;let remaining=files.length;const entry={term:state.term,cat,title,teacher,grade,desc,file:folderName,folder:isFolder||files.length>1,files:[],date:new Date().toISOString()};files.forEach(file=>{const r=new FileReader();r.onload=()=>{entry.files.push({name:file.name,path:file.webkitRelativePath||file.name,data:r.result,type:file.type});if(!--remaining){state.shares.push(entry);save();closeModal();viewShares(cat)}};r.readAsDataURL(file)})};
window.openShareFolder=function(index){const s=state.shares[index];if(!s)return;openModal(`<div class="folder-head"><div><h2>📂 ${esc(s.file||s.title)}</h2><small><b>${esc(s.teacher)}</b>${s.grade?' · '+esc(s.grade):''}</small></div></div><div class="clean-list">${(s.files||[]).map((f,n)=>`<div class="clean-upload"><div class="file-icon">📄</div><div class="file-info"><b>${esc(f.name)}</b><small>${esc(f.path)}</small></div><div class="file-actions"><button class="btn open-btn" onclick="openShareFolderFile(${index},${n})">Open</button></div></div>`).join('')}</div><div class="modal-footer"><button class="btn" onclick="viewShares('${jsq(s.cat)}')">Back</button></div>`)};
window.openShareFolderFile=function(index,n){const f=state.shares[index]?.files?.[n];if(f)openStoredFile(f.data,f.name)};
window.deleteShare=function(i){const x=state.shares[i];if(!x||!confirm('Delete this uploaded item?'))return;const cat=x.cat;state.shares.splice(i,1);save();viewShares(cat)};
window.viewShares=function(cat){const arr=state.shares.map((s,i)=>({...s,_i:i})).filter(s=>s.term===state.term&&s.cat===cat),c=jsq(cat);openModal(`<div class="folder-head"><div><h2>${esc(cat)}</h2><small>${esc(state.term)}</small></div><button id="shareAddBtn" class="btn primary add-btn">＋ Add</button></div>${arr.length?`<div class="clean-list">${arr.map(s=>`<div class="clean-upload"><div class="file-icon">${cat==='Teaching Strategies'?'🧠':cat==='Assessment Samples'?'🧾':'💡'}</div><div class="file-info"><b>${s.folder?'📂 ':''}${esc(s.title||s.file||'Evidence')}</b><small><b>${esc(s.teacher||'')}</b>${s.grade?' · '+esc(s.grade):''}${s.folder?' · '+(s.files?.length||0)+' files':''}</small></div><div class="file-actions">${s.folder?`<button class="btn open-btn" onclick="openShareFolder(${s._i})">Open Folder</button>`:(s.files?.[0]?.data?`<button class="btn open-btn" onclick="openShareFolderFile(${s._i},0)">Open</button>`:'')}<button class="btn delete-btn" onclick="deleteShare(${s._i})">Delete</button></div></div>`).join('')}</div>`:'<div class="empty-state">No uploads saved for this term yet.</div>'}<div class="modal-footer"><button class="btn" onclick="closeModal()">Close</button></div>`);setTimeout(()=>{const b=d.getElementById('shareAddBtn');if(b)b.onclick=()=>addShare(cat)},0)};
setTimeout(()=>{[...d.querySelectorAll('main > .notice')].forEach(n=>{if(/^Important:/i.test((n.textContent||'').trim()))n.remove()})},0);
})();