(()=>{
const d=document;
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('EnglishDepartmentPortfolioFiles',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('supportPlans'))r.result.createObjectStore('supportPlans',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getAll(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readonly').objectStore('supportPlans').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function put(x){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readwrite').objectStore('supportPlans').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function del(id){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('supportPlans','readwrite').objectStore('supportPlans').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
window.openSupportPlans=async function(type){const title=type==='diagnostic'?'Diagnostic Analysis':'CA Analysis';const rows=(await getAll()).filter(x=>x.type===type).sort((a,b)=>b.created-a.created);const body=`<div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:14px"><div><h3 style="margin:0">📁 ${title}</h3><small style="color:#7b878c">Upload a complete support-plan folder or individual files.</small></div><label class="btn primary" style="cursor:pointer">+ Upload Folder<input id="supportFolderInput" type="file" webkitdirectory directory multiple hidden></label></div><div id="supportRows">${rows.length?rows.map(x=>`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><div><b>${esc(x.folder)}</b><br><small>${x.files.length} file${x.files.length===1?'':'s'} · ${new Date(x.created).toLocaleDateString()}</small></div><div class="actions"><button class="btn" onclick="openSupportFolder('${x.id}')">Open</button><button class="btn danger" onclick="deleteSupportFolder('${x.id}','${type}')">Delete</button></div></div>`).join(''):'<div class="notice">No support plans uploaded yet.</div>'}</div>`;
 if(typeof openModal==='function')openModal(body);else alert('Support Plans');
 setTimeout(()=>{const input=d.getElementById('supportFolderInput');if(input)input.onchange=async()=>{const fs=[...input.files];if(!fs.length)return;const folder=(fs[0].webkitRelativePath||fs[0].name).split('/')[0];await put({id:Date.now()+'-'+Math.random().toString(36).slice(2),type,folder,created:Date.now(),files:fs.map(f=>({name:f.name,path:f.webkitRelativePath||f.name,type:f.type,data:f}))});openSupportPlans(type)}},0)
};
window.openSupportFolder=async function(id){const x=(await getAll()).find(v=>v.id===id);if(!x)return;const html=`<h3>📂 ${esc(x.folder)}</h3><p style="color:#7b878c">${x.files.length} uploaded file${x.files.length===1?'':'s'}</p>${x.files.map((f,i)=>`<div class="item" style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin:7px 0"><span>${esc(f.path)}</span><button class="btn" onclick="openSupportFile('${id}',${i})">Open</button></div>`).join('')}`;if(typeof openModal==='function')openModal(html)};
window.openSupportFile=async function(id,i){const x=(await getAll()).find(v=>v.id===id);if(!x||!x.files[i])return;const u=URL.createObjectURL(x.files[i].data);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)};
window.deleteSupportFolder=async function(id,type){if(!confirm('Delete this uploaded folder?'))return;await del(id);openSupportPlans(type)};
})();