const $=id=>document.getElementById(id);const slots=new Map();let mainCount=0,lastRequest='';const status=$('status'),create=$('createBtn');
const MASTER_PROMPT_URL='https://raw.githubusercontent.com/saidahkhwar11-lang/Interactive-English-Lessons/main/Lesson-Creation-Resources/Interactive-Lesson-Master-Prompt.txt';
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function teacher(){try{return JSON.parse(localStorage.getItem('lessonCreatorTeacher')||'null')}catch{return null}}
function showWorkspace(t){$('loginView').hidden=true;$('workspace').hidden=false;$('teacherChip').textContent=`👩‍🏫 ${t.name}`;showCreator()}
function login(){const name=$('teacherName').value.trim(),email=$('teacherEmail').value.trim();if(!name||!email){toast('Please enter teacher name and school email');return}const t={name,email};localStorage.setItem('lessonCreatorTeacher',JSON.stringify(t));showWorkspace(t)}
$('loginBtn').onclick=login;$('logoutBtn').onclick=()=>{localStorage.removeItem('lessonCreatorTeacher');location.reload()};const savedTeacher=teacher();if(savedTeacher)showWorkspace(savedTeacher);else{$('loginView').hidden=false;$('workspace').hidden=true}
function showCreator(){$('creatorView').hidden=false;$('libraryView').hidden=true}function showLibrary(){$('creatorView').hidden=true;$('libraryView').hidden=false;renderLibrary()}$('libraryBtn').onclick=showLibrary;$('newLessonBtn').onclick=showCreator;
function slotId(c){return c.dataset.slot}function initSource(c){const chk=c.querySelector('.not-from-book'),page=c.querySelector('.activity-page');if(!chk||!page)return;chk.addEventListener('change',()=>{page.disabled=chk.checked;if(chk.checked)page.value='';page.placeholder=chk.checked?'Not from the book':'e.g. 12'})}
function initSlot(c){const id=slotId(c);if(!slots.has(id))slots.set(id,[]);initSource(c);const input=c.querySelector('.slot-files'),zone=c.querySelector('.paste-zone');input?.addEventListener('change',()=>addFiles(c,[...input.files]));zone?.addEventListener('paste',e=>{const fs=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/')||f.type.startsWith('audio/')||f.type==='application/pdf');if(fs.length){e.preventDefault();addFiles(c,fs)}});zone?.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('drag')});zone?.addEventListener('dragleave',()=>zone.classList.remove('drag'));zone?.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('drag');addFiles(c,[...e.dataTransfer.files])});render(c)}
function addFiles(c,files){const id=slotId(c),a=slots.get(id)||[];files.forEach(f=>a.push({id:crypto.randomUUID?.()||Date.now()+Math.random(),file:f,url:f.type.startsWith('image/')?URL.createObjectURL(f):''}));slots.set(id,a);render(c);toast(`${files.length} file${files.length===1?'':'s'} added`)}
function render(c){const a=slots.get(slotId(c))||[],box=c.querySelector('.previews');if(!box)return;box.innerHTML='';a.forEach(x=>{const d=document.createElement('div');d.className='preview';d.innerHTML=x.url?`<img src="${x.url}" alt="activity image"><button title="Remove">×</button>`:`<div class="file">${x.file.name}</div><button title="Remove">×</button>`;d.querySelector('button').onclick=()=>{if(x.url)URL.revokeObjectURL(x.url);slots.set(slotId(c),a.filter(y=>y.id!==x.id));render(c)};box.append(d)})}
function sourceHtml(){return `<div class="activity-source"><label>📖 Activity Page <input class="activity-page" placeholder="e.g. 14"></label><label class="not-book"><input type="checkbox" class="not-from-book"> Not from the book</label></div>`}
function mainCard(n){const d=document.createElement('div');d.className='activity-card';d.dataset.slot='main-'+n;d.innerHTML=`<div class="activity-head"><div><span class="badge main">MAIN ACTIVITY ${n}</span><h3>Main Activity ${n}</h3><p>Optional — paste, drag or upload pictures, PDF pages or audio.</p></div><div><span class="ai-chip">💬 ChatGPT reads & builds it</span> <button class="remove-main" type="button">Remove</button></div></div>${sourceHtml()}<div class="paste-zone" tabindex="0"><b>📋 Add activity source here</b><span>Ctrl + V image • drag & drop • or</span><label class="browse">Browse Files<input class="slot-files" type="file" accept="image/*,.pdf,audio/*" multiple></label></div><div class="previews"></div>`;d.querySelector('.remove-main').onclick=()=>{(slots.get(d.dataset.slot)||[]).forEach(x=>x.url&&URL.revokeObjectURL(x.url));slots.delete(d.dataset.slot);d.remove();renumber()};return d}
function renumber(){const cs=[...$('mainActivities').children],old=cs.map(c=>[c.dataset.slot,slots.get(c.dataset.slot)||[]]);old.forEach(([id])=>slots.delete(id));cs.forEach((c,i)=>{const id='main-'+(i+1);c.dataset.slot=id;slots.set(id,old[i][1]);c.querySelector('.badge').textContent='MAIN ACTIVITY '+(i+1);c.querySelector('h3').textContent='Main Activity '+(i+1)});mainCount=cs.length;$('addMain').disabled=mainCount>=5}
function addMain(){if(mainCount>=5)return;const c=mainCard(mainCount+1);$('mainActivities').append(c);mainCount++;initSlot(c);$('addMain').disabled=mainCount>=5}
document.querySelectorAll('.activity-card[data-slot]').forEach(initSlot);$('addMain').onclick=addMain;addMain();addMain();
function filesFor(id){return(slots.get(id)||[]).map(x=>x.file)}function activityMeta(c){const n=c.querySelector('.not-from-book')?.checked||false;return{page:n?'':(c.querySelector('.activity-page')?.value.trim()||''),not_from_book:n}}
function sourceSummary(label,card,files){const meta=activityMeta(card);return `${label}\nPage: ${meta.not_from_book?'Not from the book':(meta.page||'Not specified')}\nFiles to attach in ChatGPT: ${files.length?files.map(f=>f.name).join(', '):'None'}`}
function downloadText(text,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Request copied')}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('Request copied')}}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('TeacherLessonCreatorDB',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('lessons'))r.result.createObjectStore('lessons',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function allLessons(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('lessons').objectStore('lessons').getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}async function delLesson(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('lessons','readwrite');tx.objectStore('lessons').delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function renderLibrary(){const all=await allLessons(),g=$('libraryGrade').value,t=$('libraryTerm').value,s=$('librarySkill').value,q=$('librarySearch').value.trim().toLowerCase(),me=teacher()?.email||'';const own=all.filter(x=>!me||x.teacher_email===me);const rows=own.filter(x=>(!g||x.grade===g)&&(!t||x.term===t)&&(!s||x.skill===s)&&(!q||`${x.title} ${x.teacher_name}`.toLowerCase().includes(q))).sort((a,b)=>(b.created_at||'').localeCompare(a.created_at||''));const grid=$('libraryGrid');grid.innerHTML='';$('libraryEmpty').hidden=rows.length>0;rows.forEach(x=>{const c=document.createElement('div');c.className='lesson-card';c.innerHTML=`<span class="eyebrow">${x.skill||'LESSON'}</span><h3>${x.title||'Untitled Lesson'}</h3><p>Teacher: ${x.teacher_name||''}</p><div class="meta-row"><span>${x.grade||''}</span><span>${x.term||''}</span>${x.pages?`<span>Pages ${x.pages}</span>`:''}</div><div class="card-actions"><button class="btn secondary deleteLesson">Delete</button></div>`;c.querySelector('.deleteLesson').onclick=async()=>{if(confirm('Delete this saved lesson from this browser?')){await delLesson(x.id);renderLibrary()}};grid.append(c)})}
[...$('grade').options].slice(1).forEach(o=>{const n=document.createElement('option');n.textContent=n.value=o.value;$('libraryGrade').append(n)});['libraryGrade','libraryTerm','librarySkill'].forEach(id=>$(id).onchange=renderLibrary);$('librarySearch').oninput=renderLibrary;
async function prepareForChatGPT(){const grade=$('grade').value,term=$('term').value,skill=$('skill').value,starterCard=document.querySelector('[data-slot="starter"]'),exitCard=document.querySelector('[data-slot="exit"]'),starter=filesFor('starter'),mains=[...$('mainActivities').children].map((c,i)=>({card:c,files:filesFor(c.dataset.slot),label:`MAIN ACTIVITY ${i+1}`})).filter(x=>x.files.length),exit=filesFor('exit');if(!grade||!skill){status.textContent='Please choose the grade and skill.';status.className='status error';return}if(!starter.length&&!mains.length&&!exit.length){status.textContent='Paste, drag or upload at least one lesson source file.';status.className='status error';return}create.disabled=true;create.textContent='💬 PREPARING CHATGPT REQUEST…';status.textContent='Loading the permanent Master Prompt and preparing your request…';status.className='status';try{let master='';try{const r=await fetch(MASTER_PROMPT_URL,{cache:'no-store'});if(r.ok)master=await r.text()}catch{}if(!master)throw new Error('Could not load the permanent Master Prompt. Please refresh and try again.');const teach=teacher();const sections=[sourceSummary('STARTER',starterCard,starter),...mains.map(m=>sourceSummary(m.label,m.card,m.files)),sourceSummary('EXIT TICKET',exitCard,exit)];lastRequest=`Please create this lesson directly in ChatGPT using the locked school Master Prompt below. I will attach the listed textbook pictures, PDF pages and/or audio files in this chat. Read the actual attachments carefully and do not invent textbook content that is not visible or audible.\n\nTEACHER\nName: ${teach?.name||''}\nEmail: ${teach?.email||''}\n\nLESSON BASICS\nGrade: ${grade}\nTerm: ${term}\nSkill: ${skill}\nLesson Title: ${$('lessonTitle').value.trim()||'Infer from source material'}\nBook Pages: ${$('bookPages').value.trim()||'Use activity page metadata'}\nSpecial Request: ${$('lessonPrompt').value.trim()||'None'}\n\nSOURCE MATERIAL ORDER\n${sections.join('\n\n')}\n\nIMPORTANT\n- Keep the source order: Starter → populated Main Activities only → Exit Ticket → Charter Connection Activity.\n- Student-facing activity instructions must explain exactly what students do and clearly show the page number or “Not from the book”.\n- Use the uploaded/attached pictures and audio as the source of truth.\n- Follow the exact bilingual school lesson-plan format in the Master Prompt.\n- Prepare the final interactive lesson and lesson plan for publishing to the Interactive-English-Lessons GitHub repository without overwriting existing lesson folders.\n\nLOCKED MASTER PROMPT\n${master}`;await copyText(lastRequest);$('afterPanel').hidden=false;status.textContent='Ready. The complete request has been copied to your clipboard.';status.className='status ready';$('afterPanel').scrollIntoView({behavior:'smooth'})}catch(e){status.textContent=e.message;status.className='status error'}finally{create.disabled=false;create.textContent='💬 PREPARE FOR CHATGPT'}}
create.onclick=prepareForChatGPT;$('copyRequestBtn').onclick=()=>lastRequest?copyText(lastRequest):toast('Prepare the request first');$('openChatGPTBtn').onclick=()=>window.open('https://chatgpt.com/','_blank','noopener');$('downloadRequestBtn').onclick=()=>lastRequest?downloadText(lastRequest,'Interactive-Lesson-ChatGPT-Request.txt'):toast('Prepare the request first');